### PR TITLE
pipeline: bump pre instead of patch

### PR DESCRIPTION
**Pull request by dweomer**
Please do not merge until #29 is merged.

Signed-off-by: Jacob Blain Christen <jacob.blain.christen@intel.com>

### CODE REVIEW

**Comment by jamesrgregg** [comment]
@cloudxxx8 @SteveOss - please review these changes that are needed to automate the tagging schema we discussed in the DevOps WG meeting this morning.

**Review by cloudxxx8 — APPROVED** [review]
LGTM

**Comment by ernestojeda** [comment]
recheck

**Comment by ernestojeda** [comment]
recheck

**Comment by jamesrgregg** [comment]
@cloudxxx8 please merge this one

**Pull request merged**
